export enum OrderStatus {
  PENDING = 'PENDENTE',
  FINISHED = 'FINALIZADO',
  CANCELLED = 'CANCELADO',
  REFUNDED = 'REEMBOLSADO',
  PROCESSING = 'PROCESSANDO',
  ON_HOLD = 'AGUARDANDO',
  FAILED = 'FALHOU',
  SHIPPED = 'ENVIADO',
  DELIVERED = 'ENTREGUE',
  RETURNED = 'DEVOLVIDO',
  OUT_FOR_DELIVERY = 'SAIU_PARA_ENTREGA',
  IN_TRANSIT = 'EM_TRÂNSITO',
}
