version: '3.8'
services:
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env.docker
    ports:
      - "3001:3001"
    depends_on:
      - db
    # Em produção/build não devemos montar o código local como read-only.

volumes:
  db_data:
    name: mini_ecommerce_db_data
