export const PAYMENT_ERRORS = {
  NOT_FOUND: 'PAGAMENTO NAO ENCONTRADO',
  INVALID_DATA: 'DADOS DE PAGAMENTO INVALIDOS',
  PROCESSING_ERROR: 'ERRO AO PROCESSAR PAGAMENTO',
  INSUFFICIENT_FUNDS: 'FUNDOS INSUFICIENTES',
  UNAUTHORIZED: 'NAO AUTORIZADO',
  TIMEOUT: 'TEMPO ESGOTADO AO PROCESSAR PAGAMENTO',
};
